version: "3.7"

services:
  master:
    build:
      context: master/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_PROXY
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - "8888:8080"
    volumes:
      - $HOME/.secrets/jenkins:/var/jenkins_home/.secrets
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/workspaces/jenkins-backup/jobs:/var/jenkins_home/jobs
      - $HOME/workspaces/jenkins-backup/userContent:/var/jenkins_home/userContent
      - /etc/localtime:/etc/localtime

  registry:
    image: registry:2
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - $HOME/workspaces/jenkins-backup/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime
      - $HOME/.secrets/auth:/auth
    environment:
      - ENV_REGISTRY_AUTH=htpasswd
      - ENV_REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - ENV_REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd  
  
  registry-web:
    image: konradkleine/docker-registry-frontend
    restart: unless-stopped
    ports:
      - 8889:80
    environment:
      - ENV_MODE_BROWSE_ONLY=true
      - ENV_REGISTRY_URL=https://docker-registry.mudryy.engineer
      - ENV_REGISTRY_TRUST_ANY_SSL=true
      - ENV_REGISTRY_BASIC_AUTH=${DOCKER_BASIC_AUTH}
      - ENV_REGISTRY_NAME=docker-registry.mudryy.engineer
      - ENV_DOCKER_REGISTRY_HOST=docker-registry.mudryy.engineer 
    volumes:
      - /etc/localtime:/etc/localtime
