version: "3.7"

services:
  master:
    build:
      context: master/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_PROXY
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - "127.0.0.1:8888:8080"
      - "50000:50000"
    volumes:
      - $HOME/.certs:/var/jenkins_home/.certs
      - $HOME/.secrets:/var/jenkins_home/.secrets
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/jenkins-backup/jobs:/var/jenkins_home/jobs
      - $HOME/jenkins-backup/userContent:/var/jenkins_home/userContent
      - /etc/localtime:/etc/localtime

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - $HOME/jenkins-backup/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime

  registry-web:
    image: konradkleine/docker-registry-frontend
    ports:
      - 8889:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_MODE_BROWSE_ONLY=true
    volumes:
      - /etc/localtime:/etc/localtime
