version: "3.7"

services:
  master:
    build:
      context: master/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_PROXY
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - "8888:8080"
    volumes:
      - $HOME/.secrets/jenkins:/var/jenkins_home/.secrets
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/workspaces/jenkins-backup/jobs:/var/jenkins_home/jobs
      - $HOME/workspaces/jenkins-backup/userContent:/var/jenkins_home/userContent
      - /etc/localtime:/etc/localtime